# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/NIM+/HGCal_NIM+/HGCal_NIM+.cache/wt [current_project]
set_property parent.project_path C:/NIM+/HGCal_NIM+/HGCal_NIM+.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/NIM+/HGCal_NIM+/HGCal_NIM+.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files C:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_5_1/design_1_axi_gpio_5_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_5_1/design_1_axi_gpio_5_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_5_1/design_1_axi_gpio_5_1.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_1/design_1_axi_gpio_6_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_1/design_1_axi_gpio_6_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_1/design_1_axi_gpio_6_1.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_3/design_1_axi_gpio_6_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_3/design_1_axi_gpio_6_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_3/design_1_axi_gpio_6_3.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_4/design_1_axi_gpio_6_4_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_4/design_1_axi_gpio_6_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_4/design_1_axi_gpio_6_4.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_5/design_1_axi_gpio_6_5_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_5/design_1_axi_gpio_6_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_6_5/design_1_axi_gpio_6_5.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_1/design_1_axi_gpio_10_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_1/design_1_axi_gpio_10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_1/design_1_axi_gpio_10_1.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_2/design_1_axi_gpio_10_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_2/design_1_axi_gpio_10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_2/design_1_axi_gpio_10_2.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_3/design_1_axi_gpio_10_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_3/design_1_axi_gpio_10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_3/design_1_axi_gpio_10_3.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_4/design_1_axi_gpio_10_4_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_4/design_1_axi_gpio_10_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_4/design_1_axi_gpio_10_4.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_5/design_1_axi_gpio_10_5_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_5/design_1_axi_gpio_10_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_5/design_1_axi_gpio_10_5.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_6/design_1_axi_gpio_10_6_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_6/design_1_axi_gpio_10_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_6/design_1_axi_gpio_10_6.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_7/design_1_axi_gpio_10_7_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_7/design_1_axi_gpio_10_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_7/design_1_axi_gpio_10_7.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_8/design_1_axi_gpio_10_8_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_8/design_1_axi_gpio_10_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_8/design_1_axi_gpio_10_8.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_9/design_1_axi_gpio_10_9_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_9/design_1_axi_gpio_10_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_9/design_1_axi_gpio_10_9.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_10/design_1_axi_gpio_10_10_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_10/design_1_axi_gpio_10_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_10_10/design_1_axi_gpio_10_10.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_0/design_1_axi_gpio_11_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_0/design_1_axi_gpio_11_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_0/design_1_axi_gpio_11_0.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_1/design_1_axi_gpio_11_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_1/design_1_axi_gpio_11_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_1/design_1_axi_gpio_11_1.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_2/design_1_axi_gpio_11_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_2/design_1_axi_gpio_11_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_2/design_1_axi_gpio_11_2.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_3/design_1_axi_gpio_11_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_3/design_1_axi_gpio_11_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_11_3/design_1_axi_gpio_11_3.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0_1/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/constrs_1/imports/Desktop/Zedboard-Master.xdc
set_property used_in_implementation false [get_files C:/NIM+/HGCal_NIM+/HGCal_NIM+.srcs/constrs_1/imports/Desktop/Zedboard-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
