# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Zedboard-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_3_0 || ORIG_REF_NAME==design_1_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_4_0 || ORIG_REF_NAME==design_1_axi_gpio_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_NIMInput_DACControl_0_0/design_1_NIMInput_DACControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_NIMInput_DACControl_0_0 || ORIG_REF_NAME==design_1_NIMInput_DACControl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_OutputLogic_0_0/design_1_OutputLogic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_OutputLogic_0_0 || ORIG_REF_NAME==design_1_OutputLogic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PulseCounter_0_0/design_1_PulseCounter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PulseCounter_0_0 || ORIG_REF_NAME==design_1_PulseCounter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DisplayLEDs_0_0/design_1_DisplayLEDs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_DisplayLEDs_0_0 || ORIG_REF_NAME==design_1_DisplayLEDs_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PulseCounter_1_0/design_1_PulseCounter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PulseCounter_1_0 || ORIG_REF_NAME==design_1_PulseCounter_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PulseCounter_2_0/design_1_PulseCounter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PulseCounter_2_0 || ORIG_REF_NAME==design_1_PulseCounter_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PulseCounter_3_0/design_1_PulseCounter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PulseCounter_3_0 || ORIG_REF_NAME==design_1_PulseCounter_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_5_1/design_1_axi_gpio_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_5_1 || ORIG_REF_NAME==design_1_axi_gpio_5_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_6_1/design_1_axi_gpio_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_6_1 || ORIG_REF_NAME==design_1_axi_gpio_6_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_6_3/design_1_axi_gpio_6_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_6_3 || ORIG_REF_NAME==design_1_axi_gpio_6_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_6_4/design_1_axi_gpio_6_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_6_4 || ORIG_REF_NAME==design_1_axi_gpio_6_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_6_5/design_1_axi_gpio_6_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_6_5 || ORIG_REF_NAME==design_1_axi_gpio_6_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_join_truth_tables_0_0/design_1_join_truth_tables_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_join_truth_tables_0_0 || ORIG_REF_NAME==design_1_join_truth_tables_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_1/design_1_axi_gpio_10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_1 || ORIG_REF_NAME==design_1_axi_gpio_10_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_2/design_1_axi_gpio_10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_2 || ORIG_REF_NAME==design_1_axi_gpio_10_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_3/design_1_axi_gpio_10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_3 || ORIG_REF_NAME==design_1_axi_gpio_10_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_4/design_1_axi_gpio_10_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_4 || ORIG_REF_NAME==design_1_axi_gpio_10_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_5/design_1_axi_gpio_10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_5 || ORIG_REF_NAME==design_1_axi_gpio_10_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_6/design_1_axi_gpio_10_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_6 || ORIG_REF_NAME==design_1_axi_gpio_10_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_7/design_1_axi_gpio_10_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_7 || ORIG_REF_NAME==design_1_axi_gpio_10_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_8/design_1_axi_gpio_10_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_8 || ORIG_REF_NAME==design_1_axi_gpio_10_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_9/design_1_axi_gpio_10_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_9 || ORIG_REF_NAME==design_1_axi_gpio_10_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_10/design_1_axi_gpio_10_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_10 || ORIG_REF_NAME==design_1_axi_gpio_10_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_11_0/design_1_axi_gpio_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_11_0 || ORIG_REF_NAME==design_1_axi_gpio_11_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_11_1/design_1_axi_gpio_11_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_11_1 || ORIG_REF_NAME==design_1_axi_gpio_11_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_11_2/design_1_axi_gpio_11_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_11_2 || ORIG_REF_NAME==design_1_axi_gpio_11_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_11_3/design_1_axi_gpio_11_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_11_3 || ORIG_REF_NAME==design_1_axi_gpio_11_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_join_truth_tables_0_1/design_1_join_truth_tables_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_join_truth_tables_0_1 || ORIG_REF_NAME==design_1_join_truth_tables_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_join_truth_tables_0_2/design_1_join_truth_tables_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_join_truth_tables_0_2 || ORIG_REF_NAME==design_1_join_truth_tables_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_join_truth_tables_0_3/design_1_join_truth_tables_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_join_truth_tables_0_3 || ORIG_REF_NAME==design_1_join_truth_tables_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0_1/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
