webtalk_init -webtalk_dir C:\\NIM+\\HGCal_NIM+\\HGCal_NIM+.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-08-31 16:07:54" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211758791_0_0_927" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "o2hmg12pbnbet7bhaq2mbk9k9u" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1498 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.615 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1630435723644" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1630435723644"
webtalk_add_data -client sdk -key uid -value "1630435755871" -context "sdk\\\\application/1630435755871"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1630435755871"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1630435755871"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1630435755871"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1630435755871"
webtalk_add_data -client sdk -key Procused -value "" -context "sdk\\\\application/1630435755871"
webtalk_add_data -client sdk -key projSize -value "96.90625" -context "sdk\\\\application/1630435755871"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1630440474910"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1630440474910"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1630440474910"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1630440474910"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1630440474910"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1630440474910"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1630440474910"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1630440474910"
webtalk_transmit -clientid 594128469 -regid "211758791_0_0_927" -xml C:\\NIM+\\HGCal_NIM+\\HGCal_NIM+.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\NIM+\\HGCal_NIM+\\HGCal_NIM+.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\NIM+\\HGCal_NIM+\\HGCal_NIM+.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
